export const GET_GRAVATAR = "GET_GRAVATAR";
export const REQUEST_AVATAR = "REQUEST_AVATAR";
export const RECEIVE_AVATAR_SUCCESS = "RECEIVE_AVATAR_SUCCESS";
export const RECEIVE_AVATAR_FAILURE = "RECEIVE_AVATAR_FAILURE";
export const HANDLE_LOGIN = "HANDLE_LOGIN";