export const HANDLE_LOGIN = 'HANDLE_LOGIN';
export const HANDLE_SUBMIT = 'HANDLE_SUBMIT';
export const REQUEST_TOKEN = 'REQUEST_TOKEN';
export const TOKEN_SUCCESS = 'TOKEN_SUCCESS';
export const TOKEN_ERROR = 'TOKEN_ERROR';
export const REQUEST_QUESTIONS = 'REQUEST_QUESTIONS';
export const QUESTIONS_SUCCESS = 'QUESTIONS_SUCCESS';
export const QUESTIONS_ERROR = 'QUESTIONS_ERROR';
